export const REQUEST_API_PENDING = 'REQUEST_API_PENDING';
export const REQUEST_API_SUCCESS = 'REQUEST_API_SUCCESS';
export const REQUEST_API_ERROR = 'REQUEST_API_ERROR';
export const TRACKING_DAY = 'TRACKING_DAY';